{% set name = "tinynetrc" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tinynetrc-{{ version }}.tar.gz
  sha256: 2b9a256d2e630643b8f0985f5e826ccf0bf3716e07e596a4f67feab363d254df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - tinynetrc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sloria/tinynetrc
  summary: Read and write .netrc files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - betolink
